apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.httpService.externalPort }}
    targetPort: {{ .Values.httpService.internalPort }}
    protocol: TCP
    name: {{ .Values.httpService.name }}
  - port: {{ .Values.httpsService.externalPort }}
    targetPort: {{ .Values.httpsService.internalPort }}
    protocol: TCP
    name: {{ .Values.httpsService.name }}
  selector:
    app: {{ template "fullname" . }}
